# Generated by Django 4.1.3 on 2022-11-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticainModel',
            fields=[
                ('politicain_id', models.AutoField(primary_key=True, serialize=False)),
                ('politicain_date', models.DateField(auto_now_add=True, null=True)),
                ('politicain_name', models.CharField(max_length=100)),
                ('politicain_gender', models.CharField(max_length=100)),
                ('politicain_position', models.CharField(max_length=100)),
                ('politicain_party', models.CharField(max_length=100)),
                ('politicain_state', models.CharField(max_length=100)),
                ('politicain_bio', models.TextField(null=True)),
                ('politicain_profile', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'politician_details',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('sentiment', models.CharField(max_length=100, null=True)),
                ('politicain_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.politicainmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
        migrations.CreateModel(
            name='AddcrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Politicain_crime_category', models.CharField(max_length=100)),
                ('politicain_crime_descrption', models.TextField()),
                ('politicain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.politicainmodel')),
            ],
            options={
                'db_table': 'crime_details',
            },
        ),
    ]
