# Generated by Django 4.1.3 on 2022-11-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='politicain_key',
        ),
        migrations.DeleteModel(
            name='AddcrimeModel',
        ),
        migrations.DeleteModel(
            name='PoliticainModel',
        ),
    ]
