# Generated by Django 4.1.3 on 2022-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_feedbackmodel_politicain_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiledataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='files/')),
            ],
            options={
                'db_table': 'excel_data',
            },
        ),
    ]
