# Generated by Django 4.1.3 on 2022-12-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_filedatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedatamodel',
            name='sentiment_graph',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
