# Generated by Django 4.1.3 on 2022-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_filedatamodel_sentiment_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedatamodel',
            name='sentiment_graph',
        ),
        migrations.AddField(
            model_name='filedatamodel',
            name='Undepressed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filedatamodel',
            name='depressed',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
