# Generated by Django 4.1.3 on 2022-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
